### ISSUE TITLE
Leave a block reference behind when teleporting (Option)

### ISSUE THREAD

**Issue by CFiggers** [mlava/todo-teleport#2]
This extension would perfectly fit my workflow if it left a block reference behind for the moved TODO. It's not too hard to do this manually since I'm selecting them anyway, so I can copy the block refs just before triggering the teleport command. But having the ability to do that automatically (perhaps as an opt-in thing in the extension's settings page) would make it even more perfect.

**Comment by mlava** [comment]
This is a great idea, and I will implement ASAP.
Will do so with a settings option, so that people who don't want the blockref don't get it, but you can switch on in prefs if that suits your workflow.
Cheers!

**Comment by cori** [comment]
I would definitely find this useful with the block ref - right now I use Workbench's `mbdnp` action which mostly works, but this would be much easier!

**Comment by mlava** [comment]
fixed in https://github.com/Roam-Research/roam-depot/pull/854

**Comment by mlava** [comment]
This PR has now been accepted and is available in Roam Depot. Cheers!
